
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(Module) {
  Module = Module || {};


var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},q;for(q in g)g.hasOwnProperty(q)&&(ca[q]=g[q]);var x="",da;x=self.location.href;_scriptDir&&(x=_scriptDir);0!==x.indexOf("blob:")?x=x.substr(0,x.lastIndexOf("/")+1):x="";da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var ea=g.print||console.log.bind(console),y=g.printErr||console.warn.bind(console);
for(q in ca)ca.hasOwnProperty(q)&&(g[q]=ca[q]);ca=null;var fa;g.wasmBinary&&(fa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var ha,ia=!1,ja="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ka(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ja)return ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function la(a,b,c){var d=B;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function na(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&oa[c];)++c;c<<=1;if(32<c-a&&ma)return ma.decode(B.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function pa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function qa(a){return 2*a.length}
function ra(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function sa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ua,va,B,D,oa,E,F,wa,xa;function ya(){var a=ha.buffer;ua=a;g.HEAP8=va=new Int8Array(a);g.HEAP16=D=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=B=new Uint8Array(a);g.HEAPU16=oa=new Uint16Array(a);g.HEAPU32=F=new Uint32Array(a);g.HEAPF32=wa=new Float32Array(a);g.HEAPF64=xa=new Float64Array(a)}var za,Aa=[],Ba=[],Ca=[],Da=[];function Ea(){var a=g.preRun.shift();Aa.unshift(a)}
var G=0,Fa=null,Ga=null;g.preloadedImages={};g.preloadedAudios={};function A(a){if(g.onAbort)g.onAbort(a);y(a);ia=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ha(){var a=H;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var H="diff.wasm";if(!Ha()){var Ia=H;H=g.locateFile?g.locateFile(Ia,x):x+Ia}
function Ja(){var a=H;try{if(a==H&&fa)return new Uint8Array(fa);if(da)return da(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}function Ka(){return fa||"function"!==typeof fetch?Promise.resolve().then(function(){return Ja()}):fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Ja()})}
function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Ja;"number"===typeof c?void 0===b.fa?za.get(c)():za.get(c)(b.fa):c(void 0===b.fa?null:b.fa)}}}function Ma(a){this.O=a-16;this.Ea=function(b){E[this.O+8>>2]=b};this.Ba=function(b){E[this.O+0>>2]=b};this.Ca=function(){E[this.O+4>>2]=0};this.Aa=function(){va[this.O+12>>0]=0};this.Da=function(){va[this.O+13>>0]=0};this.va=function(b,c){this.Ea(b);this.Ba(c);this.Ca();this.Aa();this.Da()}}var Na=0,Oa={};
function Pa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Qa(a){return this.fromWireType(F[a>>2])}var I={},J={},Ra={};function Sa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ta(a,b){a=Sa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ua(a){var b=Error,c=Ta(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Va=void 0;function Wa(a){throw new Va(a);}
function K(a,b,c){function d(h){h=c(h);h.length!==a.length&&Wa("Mismatched type converter count");for(var l=0;l<a.length;++l)L(a[l],h[l])}a.forEach(function(h){Ra[h]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(h,l){J.hasOwnProperty(h)?e[l]=J[h]:(f.push(h),I.hasOwnProperty(h)||(I[h]=[]),I[h].push(function(){e[l]=J[h];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function Xa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ya=void 0;function M(a){for(var b="";B[a];)b+=Ya[B[a++]];return b}var N=void 0;function O(a){throw new N(a);}
function L(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||O('type "'+d+'" must have a positive integer typeid pointer');if(J.hasOwnProperty(a)){if(c.ua)return;O("Cannot register type '"+d+"' twice")}J[a]=b;delete Ra[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(function(e){e()}))}function Za(a){O(a.N.R.P.name+" instance already deleted")}var $a=!1;function ab(){}
function bb(a){--a.count.value;0===a.count.value&&(a.S?a.T.X(a.S):a.R.P.X(a.O))}function cb(a){if("undefined"===typeof FinalizationGroup)return cb=function(b){return b},a;$a=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.O?bb(c):console.warn("object already deleted: "+c.O)});cb=function(b){$a.register(b,b.N,b.N);return b};ab=function(b){$a.unregister(b.N)};return cb(a)}var db=void 0,eb=[];function fb(){for(;eb.length;){var a=eb.pop();a.N.Z=!1;a["delete"]()}}
function R(){}var gb={};function hb(a,b,c){if(void 0===a[b].W){var d=a[b];a[b]=function(){a[b].W.hasOwnProperty(arguments.length)||O("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].W+")!");return a[b].W[arguments.length].apply(this,arguments)};a[b].W=[];a[b].W[d.ca]=d}}
function ib(a,b){g.hasOwnProperty(a)?(O("Cannot register public name '"+a+"' twice"),hb(g,a,a),g.hasOwnProperty(void 0)&&O("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].W[void 0]=b):g[a]=b}function jb(a,b,c,d,e,f,k,h){this.name=a;this.constructor=b;this.$=c;this.X=d;this.U=e;this.pa=f;this.ba=k;this.na=h;this.ya=[]}
function kb(a,b,c){for(;b!==c;)b.ba||O("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ba(a),b=b.U;return a}function lb(a,b){if(null===b)return this.ga&&O("null is not a valid "+this.name),0;b.N||O('Cannot pass "'+S(b)+'" as a '+this.name);b.N.O||O("Cannot pass deleted object as a pointer of type "+this.name);return kb(b.N.O,b.N.R.P,this.P)}
function mb(a,b){if(null===b){this.ga&&O("null is not a valid "+this.name);if(this.ea){var c=this.ha();null!==a&&a.push(this.X,c);return c}return 0}b.N||O('Cannot pass "'+S(b)+'" as a '+this.name);b.N.O||O("Cannot pass deleted object as a pointer of type "+this.name);!this.da&&b.N.R.da&&O("Cannot convert argument of type "+(b.N.T?b.N.T.name:b.N.R.name)+" to parameter type "+this.name);c=kb(b.N.O,b.N.R.P,this.P);if(this.ea)switch(void 0===b.N.S&&O("Passing raw pointer to smart pointer is illegal"),
this.Ia){case 0:b.N.T===this?c=b.N.S:O("Cannot convert argument of type "+(b.N.T?b.N.T.name:b.N.R.name)+" to parameter type "+this.name);break;case 1:c=b.N.S;break;case 2:if(b.N.T===this)c=b.N.S;else{var d=b.clone();c=this.za(c,T(function(){d["delete"]()}));null!==a&&a.push(this.X,c)}break;default:O("Unsupporting sharing policy")}return c}
function nb(a,b){if(null===b)return this.ga&&O("null is not a valid "+this.name),0;b.N||O('Cannot pass "'+S(b)+'" as a '+this.name);b.N.O||O("Cannot pass deleted object as a pointer of type "+this.name);b.N.R.da&&O("Cannot convert argument of type "+b.N.R.name+" to parameter type "+this.name);return kb(b.N.O,b.N.R.P,this.P)}function ob(a,b,c){if(b===c)return a;if(void 0===c.U)return null;a=ob(a,b,c.U);return null===a?null:c.na(a)}var pb={};
function qb(a,b){for(void 0===b&&O("ptr should not be undefined");a.U;)b=a.ba(b),a=a.U;return pb[b]}function rb(a,b){b.R&&b.O||Wa("makeClassHandle requires ptr and ptrType");!!b.T!==!!b.S&&Wa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return cb(Object.create(a,{N:{value:b}}))}function U(a,b,c,d){this.name=a;this.P=b;this.ga=c;this.da=d;this.ea=!1;this.X=this.za=this.ha=this.la=this.Ia=this.xa=void 0;void 0!==b.U?this.toWireType=mb:(this.toWireType=d?lb:nb,this.V=null)}
function ub(a,b){g.hasOwnProperty(a)||Wa("Replacing nonexistant public symbol");g[a]=b;g[a].ca=void 0}function vb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=za.get(b).apply(null,c);return d}}
function V(a,b){a=M(a);var c=-1!=a.indexOf("j")?vb(a,b):za.get(b);"function"!==typeof c&&O("unknown function pointer with signature "+a+": "+b);return c}var wb=void 0;function xb(a){a=yb(a);var b=M(a);W(a);return b}function zb(a,b){function c(f){e[f]||J[f]||(Ra[f]?Ra[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new wb(a+": "+d.map(xb).join([", "]));}function Ab(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function Bb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ta(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Cb=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Db(a){4<a&&0===--X[a].ia&&(X[a]=void 0,Cb.push(a))}
function T(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Cb.length?Cb.pop():X.length;X[b]={ia:1,value:a};return b}}function S(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Eb(a,b){switch(b){case 2:return function(c){return this.fromWireType(wa[c>>2])};case 3:return function(c){return this.fromWireType(xa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Fb(a,b,c){switch(b){case 0:return c?function(d){return va[d]}:function(d){return B[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return oa[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Gb={};function Hb(a){var b=Gb[a];return void 0===b?M(a):b}var Ib=[];function Jb(a){a||O("Cannot use deleted val. handle = "+a);return X[a].value}
function Kb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Lb(a){var b=Ib.length;Ib.push(a);return b}function Mb(a,b){var c=J[a];void 0===c&&O(b+" has unknown type "+xb(a));return c}function Nb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Mb(E[(b>>2)+d],"parameter "+d);return c}var Ob={},Pb=[null,[],[]];Va=g.InternalError=Ua("InternalError");for(var Qb=Array(256),Rb=0;256>Rb;++Rb)Qb[Rb]=String.fromCharCode(Rb);Ya=Qb;N=g.BindingError=Ua("BindingError");
R.prototype.isAliasOf=function(a){if(!(this instanceof R&&a instanceof R))return!1;var b=this.N.R.P,c=this.N.O,d=a.N.R.P;for(a=a.N.O;b.U;)c=b.ba(c),b=b.U;for(;d.U;)a=d.ba(a),d=d.U;return b===d&&c===a};R.prototype.clone=function(){this.N.O||Za(this);if(this.N.aa)return this.N.count.value+=1,this;var a=cb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.N;a=a(c.call(b,d,{N:{value:{count:e.count,Z:e.Z,aa:e.aa,O:e.O,R:e.R,S:e.S,T:e.T}}}));a.N.count.value+=1;a.N.Z=!1;return a};
R.prototype["delete"]=function(){this.N.O||Za(this);this.N.Z&&!this.N.aa&&O("Object already scheduled for deletion");ab(this);bb(this.N);this.N.aa||(this.N.S=void 0,this.N.O=void 0)};R.prototype.isDeleted=function(){return!this.N.O};R.prototype.deleteLater=function(){this.N.O||Za(this);this.N.Z&&!this.N.aa&&O("Object already scheduled for deletion");eb.push(this);1===eb.length&&db&&db(fb);this.N.Z=!0;return this};U.prototype.qa=function(a){this.la&&(a=this.la(a));return a};
U.prototype.ja=function(a){this.X&&this.X(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=Qa;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.ea?rb(this.P.$,{R:this.xa,O:c,T:this,S:a}):rb(this.P.$,{R:this,O:a})}var c=this.qa(a);if(!c)return this.ja(a),null;var d=qb(this.P,c);if(void 0!==d){if(0===d.N.count.value)return d.N.O=c,d.N.S=a,d.clone();d=d.clone();this.ja(a);return d}d=this.P.pa(c);d=gb[d];if(!d)return b.call(this);d=this.da?d.ma:d.pointerType;var e=ob(c,this.P,d.P);return null===e?b.call(this):this.ea?rb(d.P.$,{R:d,O:e,T:this,S:a}):rb(d.P.$,{R:d,O:e})};
g.getInheritedInstanceCount=function(){return Object.keys(pb).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in pb)pb.hasOwnProperty(b)&&a.push(pb[b]);return a};g.flushPendingDeletes=fb;g.setDelayFunction=function(a){db=a;eb.length&&db&&db(fb)};wb=g.UnboundTypeError=Ua("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
var Tb={b:function(a,b,c,d){A("Assertion failed: "+(a?ka(B,a,void 0):"")+", at: "+[b?b?ka(B,b,void 0):"":"unknown filename",c,d?d?ka(B,d,void 0):"":"unknown function"])},B:function(a){return Sb(a+16)+16},E:function(){},A:function(a,b,c){(new Ma(a)).va(b,c);Na++;throw a;},i:function(a){var b=Oa[a];delete Oa[a];var c=b.ha,d=b.X,e=b.ka,f=e.map(function(k){return k.ta}).concat(e.map(function(k){return k.Ga}));K([a],f,function(k){var h={};e.forEach(function(l,m){var n=k[m],r=l.ra,u=l.sa,z=k[m+e.length],
t=l.Fa,w=l.Ha;h[l.oa]={read:function(p){return n.fromWireType(r(u,p))},write:function(p,C){var v=[];t(w,p,z.toWireType(v,C));Pa(v)}}});return[{name:b.name,fromWireType:function(l){var m={},n;for(n in h)m[n]=h[n].read(l);d(l);return m},toWireType:function(l,m){for(var n in h)if(!(n in m))throw new TypeError('Missing field:  "'+n+'"');var r=c();for(n in h)h[n].write(r,m[n]);null!==l&&l.push(d,r);return r},argPackAdvance:8,readValueFromPointer:Qa,V:d}]})},y:function(a,b,c,d,e){var f=Xa(c);b=M(b);L(a,
{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=va;else if(2===c)h=D;else if(4===c)h=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>f])},V:null})},t:function(a,b,c,d,e,f,k,h,l,m,n,r,u){n=M(n);f=V(e,f);h&&(h=V(k,h));m&&(m=V(l,m));u=V(r,u);var z=Sa(n);ib(z,function(){zb("Cannot construct "+n+" due to unbound types",[d])});K([a,b,c],d?[d]:[],function(t){t=t[0];
if(d){var w=t.P;var p=w.$}else p=R.prototype;t=Ta(z,function(){if(Object.getPrototypeOf(this)!==C)throw new N("Use 'new' to construct "+n);if(void 0===v.Y)throw new N(n+" has no accessible constructor");var P=v.Y[arguments.length];if(void 0===P)throw new N("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(v.Y).toString()+") parameters instead!");return P.apply(this,arguments)});var C=Object.create(p,{constructor:{value:t}});t.prototype=
C;var v=new jb(n,t,C,u,w,f,h,m);w=new U(n,v,!0,!1);p=new U(n+"*",v,!1,!1);var Y=new U(n+" const*",v,!1,!0);gb[a]={pointerType:p,ma:Y};ub(z,t);return[w,p,Y]})},s:function(a,b,c,d,e,f){0<b||A("Assertion failed: undefined");var k=Ab(b,c);e=V(d,e);var h=[f],l=[];K([],[a],function(m){m=m[0];var n="constructor "+m.name;void 0===m.P.Y&&(m.P.Y=[]);if(void 0!==m.P.Y[b-1])throw new N("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
m.P.Y[b-1]=function(){zb("Cannot construct "+m.name+" due to unbound types",k)};K([],k,function(r){m.P.Y[b-1]=function(){arguments.length!==b-1&&O(n+" called with "+arguments.length+" arguments, expected "+(b-1));l.length=0;h.length=b;for(var u=1;u<b;++u)h[u]=r[u].toWireType(l,arguments[u-1]);u=e.apply(null,h);Pa(l);return r[0].fromWireType(u)};return[]});return[]})},r:function(a,b,c,d,e,f,k,h){var l=Ab(c,d);b=M(b);f=V(e,f);K([],[a],function(m){function n(){zb("Cannot call "+r+" due to unbound types",
l)}m=m[0];var r=m.name+"."+b;h&&m.P.ya.push(b);var u=m.P.$,z=u[b];void 0===z||void 0===z.W&&z.className!==m.name&&z.ca===c-2?(n.ca=c-2,n.className=m.name,u[b]=n):(hb(u,b,r),u[b].W[c-2]=n);K([],l,function(t){var w=r,p=m,C=f,v=t.length;2>v&&O("argTypes array size mismatch! Must at least get return value and 'this' types!");var Y=null!==t[1]&&null!==p,P=!1;for(p=1;p<t.length;++p)if(null!==t[p]&&void 0===t[p].V){P=!0;break}var sb="void"!==t[0].name,Q="",Z="";for(p=0;p<v-2;++p)Q+=(0!==p?", ":"")+"arg"+
p,Z+=(0!==p?", ":"")+"arg"+p+"Wired";w="return function "+Sa(w)+"("+Q+") {\nif (arguments.length !== "+(v-2)+") {\nthrowBindingError('function "+w+" called with ' + arguments.length + ' arguments, expected "+(v-2)+" args!');\n}\n";P&&(w+="var destructors = [];\n");var tb=P?"destructors":"null";Q="throwBindingError invoker fn runDestructors retType classParam".split(" ");C=[O,C,k,Pa,t[0],t[1]];Y&&(w+="var thisWired = classParam.toWireType("+tb+", this);\n");for(p=0;p<v-2;++p)w+="var arg"+p+"Wired = argType"+
p+".toWireType("+tb+", arg"+p+"); // "+t[p+2].name+"\n",Q.push("argType"+p),C.push(t[p+2]);Y&&(Z="thisWired"+(0<Z.length?", ":"")+Z);w+=(sb?"var rv = ":"")+"invoker(fn"+(0<Z.length?", ":"")+Z+");\n";if(P)w+="runDestructors(destructors);\n";else for(p=Y?1:2;p<t.length;++p)v=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==t[p].V&&(w+=v+"_dtor("+v+"); // "+t[p].name+"\n",Q.push(v+"_dtor"),C.push(t[p].V));sb&&(w+="var ret = retType.fromWireType(rv);\nreturn ret;\n");Q.push(w+"}\n");t=Bb(Q).apply(null,C);
void 0===u[b].W?(t.ca=c-2,u[b]=t):u[b].W[c-2]=t;return[]});return[]})},x:function(a,b){b=M(b);L(a,{name:b,fromWireType:function(c){var d=X[c].value;Db(c);return d},toWireType:function(c,d){return T(d)},argPackAdvance:8,readValueFromPointer:Qa,V:null})},k:function(a,b,c){c=Xa(c);b=M(b);L(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+S(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Eb(b,
c),V:null})},d:function(a,b,c,d,e){function f(m){return m}b=M(b);-1===e&&(e=4294967295);var k=Xa(c);if(0===d){var h=32-8*c;f=function(m){return m<<h>>>h}}var l=-1!=b.indexOf("unsigned");L(a,{name:b,fromWireType:f,toWireType:function(m,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+S(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+S(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+
d+", "+e+"]!");return l?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Fb(b,k,0!==d),V:null})},c:function(a,b,c){function d(f){f>>=2;var k=F;return new e(ua,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=M(c);L(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ua:!0})},l:function(a,b){b=M(b);var c="std::string"===b;L(a,{name:b,fromWireType:function(d){var e=F[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var h=d+4+
k;if(k==e||0==B[h]){f=f?ka(B,f,h-f):"";if(void 0===l)var l=f;else l+=String.fromCharCode(0),l+=f;f=h+1}}else{l=Array(e);for(k=0;k<e;++k)l[k]=String.fromCharCode(B[d+4+k]);l=l.join("")}W(d);return l},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||O("Cannot pass non-string to std::string");var k=(c&&f?function(){for(var m=0,n=0;n<e.length;++n){var r=e.charCodeAt(n);
55296<=r&&57343>=r&&(r=65536+((r&1023)<<10)|e.charCodeAt(++n)&1023);127>=r?++m:m=2047>=r?m+2:65535>=r?m+3:m+4}return m}:function(){return e.length})(),h=Sb(4+k+1);F[h>>2]=k;if(c&&f)la(e,h+4,k+1);else if(f)for(f=0;f<k;++f){var l=e.charCodeAt(f);255<l&&(W(h),O("String has UTF-16 code units that do not fit in 8 bits"));B[h+4+f]=l}else for(f=0;f<k;++f)B[h+4+f]=e[f];null!==d&&d.push(W,h);return h},argPackAdvance:8,readValueFromPointer:Qa,V:function(d){W(d)}})},g:function(a,b,c){c=M(c);if(2===b){var d=
na;var e=pa;var f=qa;var k=function(){return oa};var h=1}else 4===b&&(d=ra,e=sa,f=ta,k=function(){return F},h=2);L(a,{name:c,fromWireType:function(l){for(var m=F[l>>2],n=k(),r,u=l+4,z=0;z<=m;++z){var t=l+4+z*b;if(z==m||0==n[t>>h])u=d(u,t-u),void 0===r?r=u:(r+=String.fromCharCode(0),r+=u),u=t+b}W(l);return r},toWireType:function(l,m){"string"!==typeof m&&O("Cannot pass non-string to C++ string type "+c);var n=f(m),r=Sb(4+n+b);F[r>>2]=n>>h;e(m,r+4,n+b);null!==l&&l.push(W,r);return r},argPackAdvance:8,
readValueFromPointer:Qa,V:function(l){W(l)}})},m:function(a,b,c,d,e,f){Oa[a]={name:M(b),ha:V(c,d),X:V(e,f),ka:[]}},e:function(a,b,c,d,e,f,k,h,l,m){Oa[a].ka.push({oa:M(b),ta:c,ra:V(d,e),sa:f,Ga:k,Fa:V(h,l),Ha:m})},z:function(a,b){b=M(b);L(a,{wa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},n:function(a,b,c,d){a=Ib[a];b=Jb(b);c=Hb(c);a(b,c,null,d)},f:Db,p:function(a){if(0===a)return T(Kb());a=Hb(a);return T(Kb()[a])},o:function(a,b){b=Nb(a,b);for(var c=b[0],d=c.name+
"_$"+b.slice(1).map(function(m){return m.name}).join("_")+"$",e=["retType"],f=[c],k="",h=0;h<a-1;++h)k+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),f.push(b[1+h]);d="return function "+Sa("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var l=0;for(h=0;h<a-1;++h)d+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(l?"+"+l:"")+");\n",l+=b[h+1].argPackAdvance;d+="    var rv = handle[name]("+k+");\n";for(h=0;h<a-1;++h)b[h+1].deleteObject&&(d+="    argType"+h+".deleteObject(arg"+h+
");\n");c.wa||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Bb(e).apply(null,f);return Lb(a)},h:function(a){4<a&&(X[a].ia+=1)},D:function(a,b,c,d){a=Jb(a);var e=Ob[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)k+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+
f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",k+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Mb,g,T);Ob[b]=e}return e(a,c,d)},C:function(){return T([])},q:function(a,b){a=Mb(a,"_emval_take_value");a=a.readValueFromPointer(b);return T(a)},a:function(){A()},v:function(a,b,c){B.copyWithin(a,b,b+c)},w:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ha.grow(Math.min(2147483648,d)-ua.byteLength+65535>>>16);ya();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},j:function(a,b,c,d){for(var e=0,f=0;f<c;f++){for(var k=E[b+8*f>>2],h=E[b+(8*f+4)>>2],l=0;l<h;l++){var m=B[k+l],n=Pb[a];0===m||10===m?((1===a?ea:y)(ka(n,0)),n.length=0):n.push(m)}e+=h}E[d>>2]=e;return 0},u:function(){}};
(function(){function a(e){g.asm=e.exports;ha=g.asm.F;ya();za=g.asm.I;Ba.unshift(g.asm.G);G--;g.monitorRunDependencies&&g.monitorRunDependencies(G);0==G&&(null!==Fa&&(clearInterval(Fa),Fa=null),Ga&&(e=Ga,Ga=null,e()))}function b(e){a(e.instance)}function c(e){return Ka().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){y("failed to asynchronously prepare wasm: "+f);A(f)})}var d={a:Tb};G++;g.monitorRunDependencies&&g.monitorRunDependencies(G);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return fa||"function"!==typeof WebAssembly.instantiateStreaming||Ha()||"function"!==typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){y("wasm streaming compile failed: "+f);y("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.G).apply(null,arguments)};var Sb=g._malloc=function(){return(Sb=g._malloc=g.asm.H).apply(null,arguments)},W=g._free=function(){return(W=g._free=g.asm.J).apply(null,arguments)},yb=g.___getTypeName=function(){return(yb=g.___getTypeName=g.asm.K).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.L).apply(null,arguments)};
g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.M).apply(null,arguments)};var Ub;Ga=function Vb(){Ub||Wb();Ub||(Ga=Vb)};
function Wb(){function a(){if(!Ub&&(Ub=!0,g.calledRun=!0,!ia)){La(Ba);La(Ca);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Da.unshift(b)}La(Da)}}if(!(0<G)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ea();La(Aa);0<G||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}
g.run=Wb;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Wb();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
