
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var q={},u;for(u in g)g.hasOwnProperty(u)&&(q[u]=g[u]);var ca="object"===typeof window,v="function"===typeof importScripts,x="",da,ea,fa,y,z;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)x=v?require("path").dirname(x)+"/":__dirname+"/",da=function(a,b){y||(y=require("fs"));z||(z=require("path"));a=z.normalize(a);return y.readFileSync(a,b?null:"utf8")},fa=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||A("Assertion failed: undefined");return a},ea=function(a,b,c){y||(y=require("fs"));z||(z=require("path"));a=z.normalize(a);y.readFile(a,function(d,e){d?c(d):b(e.buffer)})},
1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",function(a){throw a;}),g.inspect=function(){return"[Emscripten Module object]"};else if(ca||v)v?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),0!==x.indexOf("blob:")?x=x.substr(0,x.replace(/[?#].*/,"").lastIndexOf("/")+1):x="",da=function(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(fa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ea=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ha=g.print||console.log.bind(console),B=g.printErr||console.warn.bind(console);
for(u in q)q.hasOwnProperty(u)&&(g[u]=q[u]);q=null;var C;g.wasmBinary&&(C=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var ia,ka=!1,la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&la)return la.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function na(a,b,c){var d=D;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function pa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&qa[c];)++c;c<<=1;if(32<c-a&&oa)return oa.decode(D.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=E[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function ra(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)E[b>>1]=a.charCodeAt(e),b+=2;E[b>>1]=0;return b-d}function sa(a){return 2*a.length}
function ta(a,b){for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function ua(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var wa,xa,D,E,qa,F,I,ya,za;function Aa(){var a=ia.buffer;wa=a;g.HEAP8=xa=new Int8Array(a);g.HEAP16=E=new Int16Array(a);g.HEAP32=F=new Int32Array(a);g.HEAPU8=D=new Uint8Array(a);g.HEAPU16=qa=new Uint16Array(a);g.HEAPU32=I=new Uint32Array(a);g.HEAPF32=ya=new Float32Array(a);g.HEAPF64=za=new Float64Array(a)}var Ba,Ca=[],Da=[],Ea=[];function Fa(){var a=g.preRun.shift();Ca.unshift(a)}
var J=0,Ga=null,Ha=null;g.preloadedImages={};g.preloadedAudios={};function A(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";B(a);ka=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ia(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="diff.wasm";if(!Ia()){var Ja=K;K=g.locateFile?g.locateFile(Ja,x):x+Ja}
function Ka(){var a=K;try{if(a==K&&C)return new Uint8Array(C);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function La(){if(!C&&(ca||v)){if("function"===typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ka()});if(ea)return new Promise(function(a,b){ea(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ka()})}
function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Ka;"number"===typeof c?void 0===b.ga?Na(c)():Na(c)(b.ga):c(void 0===b.ga?null:b.ga)}}}var Oa=[];function Na(a){var b=Oa[a];b||(a>=Oa.length&&(Oa.length=a+1),Oa[a]=b=Ba.get(a));return b}
function Pa(a){this.O=a-16;this.Fa=function(b){F[this.O+4>>2]=b};this.Ca=function(b){F[this.O+8>>2]=b};this.Da=function(){F[this.O>>2]=0};this.Ba=function(){xa[this.O+12>>0]=0};this.Ea=function(){xa[this.O+13>>0]=0};this.wa=function(b,c){this.Fa(b);this.Ca(c);this.Da();this.Ba();this.Ea()}}var Qa=0,Ra={};function Sa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ta(a){return this.fromWireType(I[a>>2])}var L={},M={},Ua={};
function Va(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Wa(a,b){a=Va(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Xa(a){var b=Error,c=Wa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ya=void 0;function Za(a){throw new Ya(a);}
function N(a,b,c){function d(h){h=c(h);h.length!==a.length&&Za("Mismatched type converter count");for(var l=0;l<a.length;++l)O(a[l],h[l])}a.forEach(function(h){Ua[h]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(h,l){M.hasOwnProperty(h)?e[l]=M[h]:(f.push(h),L.hasOwnProperty(h)||(L[h]=[]),L[h].push(function(){e[l]=M[h];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function $a(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var ab=void 0;function P(a){for(var b="";D[a];)b+=ab[D[a++]];return b}var Q=void 0;function R(a){throw new Q(a);}
function O(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||R('type "'+d+'" must have a positive integer typeid pointer');if(M.hasOwnProperty(a)){if(c.va)return;R("Cannot register type '"+d+"' twice")}M[a]=b;delete Ua[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(function(e){e()}))}function bb(a){R(a.N.R.P.name+" instance already deleted")}var cb=!1;function db(){}
function eb(a){--a.count.value;0===a.count.value&&(a.S?a.T.X(a.S):a.R.P.X(a.O))}function fb(a){if("undefined"===typeof FinalizationGroup)return fb=function(b){return b},a;cb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.O?eb(c):console.warn("object already deleted: "+c.O)});fb=function(b){cb.register(b,b.N,b.N);return b};db=function(b){cb.unregister(b.N)};return fb(a)}var gb=void 0,hb=[];function ib(){for(;hb.length;){var a=hb.pop();a.N.Z=!1;a["delete"]()}}
function S(){}var jb={};function kb(a,b,c){if(void 0===a[b].W){var d=a[b];a[b]=function(){a[b].W.hasOwnProperty(arguments.length)||R("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].W+")!");return a[b].W[arguments.length].apply(this,arguments)};a[b].W=[];a[b].W[d.da]=d}}
function lb(a,b){g.hasOwnProperty(a)?(R("Cannot register public name '"+a+"' twice"),kb(g,a,a),g.hasOwnProperty(void 0)&&R("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].W[void 0]=b):g[a]=b}function mb(a,b,c,d,e,f,k,h){this.name=a;this.constructor=b;this.$=c;this.X=d;this.U=e;this.qa=f;this.ba=k;this.oa=h;this.za=[]}
function nb(a,b,c){for(;b!==c;)b.ba||R("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ba(a),b=b.U;return a}function ob(a,b){if(null===b)return this.ha&&R("null is not a valid "+this.name),0;b.N||R('Cannot pass "'+T(b)+'" as a '+this.name);b.N.O||R("Cannot pass deleted object as a pointer of type "+this.name);return nb(b.N.O,b.N.R.P,this.P)}
function pb(a,b){if(null===b){this.ha&&R("null is not a valid "+this.name);if(this.fa){var c=this.ia();null!==a&&a.push(this.X,c);return c}return 0}b.N||R('Cannot pass "'+T(b)+'" as a '+this.name);b.N.O||R("Cannot pass deleted object as a pointer of type "+this.name);!this.ea&&b.N.R.ea&&R("Cannot convert argument of type "+(b.N.T?b.N.T.name:b.N.R.name)+" to parameter type "+this.name);c=nb(b.N.O,b.N.R.P,this.P);if(this.fa)switch(void 0===b.N.S&&R("Passing raw pointer to smart pointer is illegal"),
this.Ja){case 0:b.N.T===this?c=b.N.S:R("Cannot convert argument of type "+(b.N.T?b.N.T.name:b.N.R.name)+" to parameter type "+this.name);break;case 1:c=b.N.S;break;case 2:if(b.N.T===this)c=b.N.S;else{var d=b.clone();c=this.Aa(c,U(function(){d["delete"]()}));null!==a&&a.push(this.X,c)}break;default:R("Unsupporting sharing policy")}return c}
function qb(a,b){if(null===b)return this.ha&&R("null is not a valid "+this.name),0;b.N||R('Cannot pass "'+T(b)+'" as a '+this.name);b.N.O||R("Cannot pass deleted object as a pointer of type "+this.name);b.N.R.ea&&R("Cannot convert argument of type "+b.N.R.name+" to parameter type "+this.name);return nb(b.N.O,b.N.R.P,this.P)}function rb(a,b,c){if(b===c)return a;if(void 0===c.U)return null;a=rb(a,b,c.U);return null===a?null:c.oa(a)}var sb={};
function tb(a,b){for(void 0===b&&R("ptr should not be undefined");a.U;)b=a.ba(b),a=a.U;return sb[b]}function ub(a,b){b.R&&b.O||Za("makeClassHandle requires ptr and ptrType");!!b.T!==!!b.S&&Za("Both smartPtrType and smartPtr must be specified");b.count={value:1};return fb(Object.create(a,{N:{value:b}}))}function V(a,b,c,d){this.name=a;this.P=b;this.ha=c;this.ea=d;this.fa=!1;this.X=this.Aa=this.ia=this.ma=this.Ja=this.ya=void 0;void 0!==b.U?this.toWireType=pb:(this.toWireType=d?ob:qb,this.V=null)}
function vb(a,b){g.hasOwnProperty(a)||Za("Replacing nonexistant public symbol");g[a]=b;g[a].da=void 0}function wb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=Na(b).apply(null,c);return d}}function X(a,b){a=P(a);var c=a.includes("j")?wb(a,b):Na(b);"function"!==typeof c&&R("unknown function pointer with signature "+a+": "+b);return c}
var zb=void 0;function Ab(a){a=Bb(a);var b=P(a);Y(a);return b}function Cb(a,b){function c(f){e[f]||M[f]||(Ua[f]?Ua[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new zb(a+": "+d.map(Ab).join([", "]));}function Db(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Eb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Wa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Fb(a,b,c,d,e){var f=b.length;2>f&&R("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,h=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].V){h=!0;break}var l="void"!==b[0].name,m="",n="";for(c=0;c<f-2;++c)m+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Va(a)+"("+m+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";h&&(a+="var destructors = [];\n");var p=h?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[R,d,e,Sa,b[0],b[1]];k&&(a+="var thisWired = classParam.toWireType("+p+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+p+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),d.push(b[c+2]);k&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(l?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(h)a+=
"runDestructors(destructors);\n";else for(c=k?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].V&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",m.push(f+"_dtor"),d.push(b[c].V));l&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return Eb(m).apply(null,d)}var Gb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Hb(a){4<a&&0===--Z[a].ja&&(Z[a]=void 0,Gb.push(a))}
function Ib(a){a||R("Cannot use deleted val. handle = "+a);return Z[a].value}function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Gb.length?Gb.pop():Z.length;Z[b]={ja:1,value:a};return b}}function T(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Jb(a,b){switch(b){case 2:return function(c){return this.fromWireType(ya[c>>2])};case 3:return function(c){return this.fromWireType(za[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Kb(a,b,c){switch(b){case 0:return c?function(d){return xa[d]}:function(d){return D[d]};case 1:return c?function(d){return E[d>>1]}:function(d){return qa[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Lb={};function Mb(a){var b=Lb[a];return void 0===b?P(a):b}var Nb=[];function Ob(){return"object"===typeof globalThis?globalThis:Function("return this")()}
function Pb(a){var b=Nb.length;Nb.push(a);return b}function Qb(a,b){var c=M[a];void 0===c&&R(b+" has unknown type "+Ab(a));return c}function Rb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Qb(F[(b>>2)+d],"parameter "+d);return c}var Sb={},Tb=[null,[],[]];Ya=g.InternalError=Xa("InternalError");for(var Ub=Array(256),Vb=0;256>Vb;++Vb)Ub[Vb]=String.fromCharCode(Vb);ab=Ub;Q=g.BindingError=Xa("BindingError");
S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.N.R.P,c=this.N.O,d=a.N.R.P;for(a=a.N.O;b.U;)c=b.ba(c),b=b.U;for(;d.U;)a=d.ba(a),d=d.U;return b===d&&c===a};S.prototype.clone=function(){this.N.O||bb(this);if(this.N.aa)return this.N.count.value+=1,this;var a=fb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.N;a=a(c.call(b,d,{N:{value:{count:e.count,Z:e.Z,aa:e.aa,O:e.O,R:e.R,S:e.S,T:e.T}}}));a.N.count.value+=1;a.N.Z=!1;return a};
S.prototype["delete"]=function(){this.N.O||bb(this);this.N.Z&&!this.N.aa&&R("Object already scheduled for deletion");db(this);eb(this.N);this.N.aa||(this.N.S=void 0,this.N.O=void 0)};S.prototype.isDeleted=function(){return!this.N.O};S.prototype.deleteLater=function(){this.N.O||bb(this);this.N.Z&&!this.N.aa&&R("Object already scheduled for deletion");hb.push(this);1===hb.length&&gb&&gb(ib);this.N.Z=!0;return this};V.prototype.ra=function(a){this.ma&&(a=this.ma(a));return a};
V.prototype.ka=function(a){this.X&&this.X(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=Ta;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.fa?ub(this.P.$,{R:this.ya,O:c,T:this,S:a}):ub(this.P.$,{R:this,O:a})}var c=this.ra(a);if(!c)return this.ka(a),null;var d=tb(this.P,c);if(void 0!==d){if(0===d.N.count.value)return d.N.O=c,d.N.S=a,d.clone();d=d.clone();this.ka(a);return d}d=this.P.qa(c);d=jb[d];if(!d)return b.call(this);d=this.ea?d.na:d.pointerType;var e=rb(c,this.P,d.P);return null===e?b.call(this):this.fa?ub(d.P.$,{R:d,O:e,T:this,S:a}):ub(d.P.$,{R:d,O:e})};
g.getInheritedInstanceCount=function(){return Object.keys(sb).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in sb)sb.hasOwnProperty(b)&&a.push(sb[b]);return a};g.flushPendingDeletes=ib;g.setDelayFunction=function(a){gb=a;hb.length&&gb&&gb(ib)};zb=g.UnboundTypeError=Xa("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Xb={e:function(a,b,c,d){A("Assertion failed: "+(a?ma(D,a,void 0):"")+", at: "+[b?b?ma(D,b,void 0):"":"unknown filename",c,d?d?ma(D,d,void 0):"":"unknown function"])},C:function(a){return Wb(a+16)+16},B:function(a,b,c){(new Pa(a)).wa(b,c);Qa++;throw a;},i:function(a){var b=Ra[a];delete Ra[a];var c=b.ia,d=b.X,e=b.la,f=e.map(function(k){return k.ua}).concat(e.map(function(k){return k.Ha}));N([a],f,function(k){var h={};e.forEach(function(l,m){var n=k[m],p=l.sa,r=l.ta,w=k[m+e.length],t=l.Ga,W=l.Ia;
h[l.pa]={read:function(G){return n.fromWireType(p(r,G))},write:function(G,ja){var H=[];t(W,G,w.toWireType(H,ja));Sa(H)}}});return[{name:b.name,fromWireType:function(l){var m={},n;for(n in h)m[n]=h[n].read(l);d(l);return m},toWireType:function(l,m){for(var n in h)if(!(n in m))throw new TypeError('Missing field:  "'+n+'"');var p=c();for(n in h)h[n].write(p,m[n]);null!==l&&l.push(d,p);return p},argPackAdvance:8,readValueFromPointer:Ta,V:d}]})},u:function(){},z:function(a,b,c,d,e){var f=$a(c);b=P(b);
O(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=xa;else if(2===c)h=E;else if(4===c)h=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>f])},V:null})},t:function(a,b,c,d,e,f,k,h,l,m,n,p,r){n=P(n);f=X(e,f);h&&(h=X(k,h));m&&(m=X(l,m));r=X(p,r);var w=Va(n);lb(w,function(){Cb("Cannot construct "+n+" due to unbound types",[d])});N([a,b,c],d?[d]:[],function(t){t=
t[0];if(d){var W=t.P;var G=W.$}else G=S.prototype;t=Wa(w,function(){if(Object.getPrototypeOf(this)!==ja)throw new Q("Use 'new' to construct "+n);if(void 0===H.Y)throw new Q(n+" has no accessible constructor");var xb=H.Y[arguments.length];if(void 0===xb)throw new Q("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(H.Y).toString()+") parameters instead!");return xb.apply(this,arguments)});var ja=Object.create(G,{constructor:{value:t}});
t.prototype=ja;var H=new mb(n,t,ja,r,W,f,h,m);W=new V(n,H,!0,!1);G=new V(n+"*",H,!1,!1);var yb=new V(n+" const*",H,!1,!0);jb[a]={pointerType:G,na:yb};vb(w,t);return[W,G,yb]})},s:function(a,b,c,d,e,f){0<b||A("Assertion failed: undefined");var k=Db(b,c);e=X(d,e);N([],[a],function(h){h=h[0];var l="constructor "+h.name;void 0===h.P.Y&&(h.P.Y=[]);if(void 0!==h.P.Y[b-1])throw new Q("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+h.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
h.P.Y[b-1]=function(){Cb("Cannot construct "+h.name+" due to unbound types",k)};N([],k,function(m){m.splice(1,0,null);h.P.Y[b-1]=Fb(l,m,null,e,f);return[]});return[]})},r:function(a,b,c,d,e,f,k,h){var l=Db(c,d);b=P(b);f=X(e,f);N([],[a],function(m){function n(){Cb("Cannot call "+p+" due to unbound types",l)}m=m[0];var p=m.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.P.za.push(b);var r=m.P.$,w=r[b];void 0===w||void 0===w.W&&w.className!==m.name&&w.da===c-2?(n.da=c-2,n.className=m.name,
r[b]=n):(kb(r,b,p),r[b].W[c-2]=n);N([],l,function(t){t=Fb(p,t,m,f,k);void 0===r[b].W?(t.da=c-2,r[b]=t):r[b].W[c-2]=t;return[]});return[]})},y:function(a,b){b=P(b);O(a,{name:b,fromWireType:function(c){var d=Ib(c);Hb(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:Ta,V:null})},k:function(a,b,c){c=$a(c);b=P(b);O(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+
T(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Jb(b,c),V:null})},c:function(a,b,c,d,e){function f(m){return m}b=P(b);-1===e&&(e=4294967295);var k=$a(c);if(0===d){var h=32-8*c;f=function(m){return m<<h>>>h}}var l=b.includes("unsigned");O(a,{name:b,fromWireType:f,toWireType:function(m,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+T(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+T(n)+'" from JS side to C/C++ side to an argument of type "'+
b+'", which is outside the valid range ['+d+", "+e+"]!");return l?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Kb(b,k,0!==d),V:null})},b:function(a,b,c){function d(f){f>>=2;var k=I;return new e(wa,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);O(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{va:!0})},l:function(a,b){b=P(b);var c="std::string"===b;O(a,{name:b,fromWireType:function(d){var e=I[d>>2];
if(c)for(var f=d+4,k=0;k<=e;++k){var h=d+4+k;if(k==e||0==D[h]){f=f?ma(D,f,h-f):"";if(void 0===l)var l=f;else l+=String.fromCharCode(0),l+=f;f=h+1}}else{l=Array(e);for(k=0;k<e;++k)l[k]=String.fromCharCode(D[d+4+k]);l=l.join("")}Y(d);return l},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||R("Cannot pass non-string to std::string");var k=(c&&f?function(){for(var m=
0,n=0;n<e.length;++n){var p=e.charCodeAt(n);55296<=p&&57343>=p&&(p=65536+((p&1023)<<10)|e.charCodeAt(++n)&1023);127>=p?++m:m=2047>=p?m+2:65535>=p?m+3:m+4}return m}:function(){return e.length})(),h=Wb(4+k+1);I[h>>2]=k;if(c&&f)na(e,h+4,k+1);else if(f)for(f=0;f<k;++f){var l=e.charCodeAt(f);255<l&&(Y(h),R("String has UTF-16 code units that do not fit in 8 bits"));D[h+4+f]=l}else for(f=0;f<k;++f)D[h+4+f]=e[f];null!==d&&d.push(Y,h);return h},argPackAdvance:8,readValueFromPointer:Ta,V:function(d){Y(d)}})},
g:function(a,b,c){c=P(c);if(2===b){var d=pa;var e=ra;var f=sa;var k=function(){return qa};var h=1}else 4===b&&(d=ta,e=ua,f=va,k=function(){return I},h=2);O(a,{name:c,fromWireType:function(l){for(var m=I[l>>2],n=k(),p,r=l+4,w=0;w<=m;++w){var t=l+4+w*b;if(w==m||0==n[t>>h])r=d(r,t-r),void 0===p?p=r:(p+=String.fromCharCode(0),p+=r),r=t+b}Y(l);return p},toWireType:function(l,m){"string"!==typeof m&&R("Cannot pass non-string to C++ string type "+c);var n=f(m),p=Wb(4+n+b);I[p>>2]=n>>h;e(m,p+4,n+b);null!==
l&&l.push(Y,p);return p},argPackAdvance:8,readValueFromPointer:Ta,V:function(l){Y(l)}})},m:function(a,b,c,d,e,f){Ra[a]={name:P(b),ia:X(c,d),X:X(e,f),la:[]}},d:function(a,b,c,d,e,f,k,h,l,m){Ra[a].la.push({pa:P(b),ua:c,sa:X(d,e),ta:f,Ha:k,Ga:X(h,l),Ia:m})},A:function(a,b){b=P(b);O(a,{xa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},n:function(a,b,c,d){a=Nb[a];b=Ib(b);c=Mb(c);a(b,c,null,d)},f:Hb,p:function(a){if(0===a)return U(Ob());a=Mb(a);return U(Ob()[a])},o:function(a,
b){b=Rb(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(m){return m.name}).join("_")+"$",e=["retType"],f=[c],k="",h=0;h<a-1;++h)k+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),f.push(b[1+h]);d="return function "+Va("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var l=0;for(h=0;h<a-1;++h)d+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(l?"+"+l:"")+");\n",l+=b[h+1].argPackAdvance;d+="    var rv = handle[name]("+k+");\n";for(h=0;h<a-1;++h)b[h+1].deleteObject&&(d+=
"    argType"+h+".deleteObject(arg"+h+");\n");c.xa||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Eb(e).apply(null,f);return Pb(a)},h:function(a){4<a&&(Z[a].ja+=1)},E:function(a,b,c,d){a=Ib(a);var e=Sb[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)k+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+
f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","valueToHandle",k+("var obj = new constructor("+e+");\nreturn valueToHandle(obj);\n}\n")))(Qb,g,U);Sb[b]=e}return e(a,c,d)},D:function(){return U([])},q:function(a,b){a=Qb(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},a:function(){A("")},w:function(a,b,c){D.copyWithin(a,b,b+c)},x:function(a){var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=
1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ia.grow(Math.min(2147483648,d)-wa.byteLength+65535>>>16);Aa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},j:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var k=F[b>>2],h=F[b+4>>2];b+=8;for(var l=0;l<h;l++){var m=D[k+l],n=Tb[a];0===m||10===m?((1===a?ha:B)(ma(n,0)),n.length=0):n.push(m)}e+=h}F[d>>2]=e;return 0},v:function(){}};
(function(){function a(e){g.asm=e.exports;ia=g.asm.F;Aa();Ba=g.asm.I;Da.unshift(g.asm.G);J--;g.monitorRunDependencies&&g.monitorRunDependencies(J);0==J&&(null!==Ga&&(clearInterval(Ga),Ga=null),Ha&&(e=Ha,Ha=null,e()))}function b(e){a(e.instance)}function c(e){return La().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){B("failed to asynchronously prepare wasm: "+f);A(f)})}var d={a:Xb};J++;g.monitorRunDependencies&&g.monitorRunDependencies(J);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return B("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return C||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||K.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){B("wasm streaming compile failed: "+f);B("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.G).apply(null,arguments)};var Wb=g._malloc=function(){return(Wb=g._malloc=g.asm.H).apply(null,arguments)},Y=g._free=function(){return(Y=g._free=g.asm.J).apply(null,arguments)},Bb=g.___getTypeName=function(){return(Bb=g.___getTypeName=g.asm.K).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.L).apply(null,arguments)};
g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.M).apply(null,arguments)};var Yb;Ha=function Zb(){Yb||$b();Yb||(Ha=Zb)};
function $b(){function a(){if(!Yb&&(Yb=!0,g.calledRun=!0,!ka)){Ma(Da);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ea.unshift(b)}Ma(Ea)}}if(!(0<J)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Fa();Ma(Ca);0<J||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=$b;
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();$b();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
