
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});var r={},t;for(t in f)f.hasOwnProperty(t)&&(r[t]=f[t]);var u=!1,v=!1,ca=!1,da=!1;u="object"===typeof window;v="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!u&&!ca&&!v;var w="",ea,x,fa,ha;
if(ca)w=v?require("path").dirname(w)+"/":__dirname+"/",ea=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},x=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",B),f.inspect=function(){return"[Emscripten Module object]"};else if(da)"undefined"!=
typeof read&&(ea=function(a){return read(a)}),x=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(u||v)v?w=self.location.href:document.currentScript&&(w=document.currentScript.src),_scriptDir&&(w=_scriptDir),0!==w.indexOf("blob:")?w=w.substr(0,
w.lastIndexOf("/")+1):w="",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(x=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ia=f.print||console.log.bind(console),C=f.printErr||console.warn.bind(console);for(t in r)r.hasOwnProperty(t)&&(f[t]=r[t]);r=null;var D;f.wasmBinary&&(D=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);
"object"!==typeof WebAssembly&&B("no native wasm support detected");var E,G=new WebAssembly.Table({initial:49,maximum:49,element:"anyfunc"}),ja=!1;function assert(a,b){a||B("Assertion failed: "+b)}var la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function H(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&la)return la.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ma(a,b,c){var d=I;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var na="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function oa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&pa[c];)++c;c<<=1;if(32<c-a&&na)return na.decode(I.subarray(a,c));c=0;for(d="";;){var e=J[a+2*c>>1];if(0==e||c==b/2)return d;++c;d+=String.fromCharCode(e)}}function qa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)J[b>>1]=a.charCodeAt(e),b+=2;J[b>>1]=0;return b-d}function ra(a){return 2*a.length}
function sa(a,b){for(var c=0,d="";!(c>=b/4);){var e=K[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function ta(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}K[b>>2]=g;b+=4;if(b+4>c)break}K[b>>2]=0;return b-d}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var L,M,I,J,pa,K,N,va,wa;function xa(a){L=a;f.HEAP8=M=new Int8Array(a);f.HEAP16=J=new Int16Array(a);f.HEAP32=K=new Int32Array(a);f.HEAPU8=I=new Uint8Array(a);f.HEAPU16=pa=new Uint16Array(a);f.HEAPU32=N=new Uint32Array(a);f.HEAPF32=va=new Float32Array(a);f.HEAPF64=wa=new Float64Array(a)}var ya=f.INITIAL_MEMORY||16777216;f.wasmMemory?E=f.wasmMemory:E=new WebAssembly.Memory({initial:ya/65536,maximum:32768});
E&&(L=E.buffer);ya=L.byteLength;xa(L);var za=[],Aa=[],Ba=[],Ca=[];function Da(){var a=f.preRun.shift();za.unshift(a)}var O=0,Ea=null,P=null;f.preloadedImages={};f.preloadedAudios={};function B(a){if(f.onAbort)f.onAbort(a);C(a);ja=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Fa(a){var b=Q;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ga(){return Fa("data:application/octet-stream;base64,")}var Q="metrics.wasm";
if(!Ga()){var Ha=Q;Q=f.locateFile?f.locateFile(Ha,w):w+Ha}function Ia(){try{if(D)return new Uint8Array(D);if(x)return x(Q);throw"both async and sync fetching of the wasm failed";}catch(a){B(a)}}function Ja(){return D||!u&&!v||"function"!==typeof fetch||Fa("file://")?Promise.resolve().then(Ia):fetch(Q,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Q+"'";return a.arrayBuffer()}).catch(function(){return Ia()})}
function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.S;"number"===typeof c?void 0===b.L?G.get(c)():G.get(c)(b.L):c(void 0===b.L?null:b.L)}}}function La(a){this.K=a-16;this.fa=function(b){K[this.K+8>>2]=b};this.ba=function(b){K[this.K+0>>2]=b};this.da=function(){K[this.K+4>>2]=0};this.aa=function(){M[this.K+12>>0]=0};this.ea=function(){M[this.K+13>>0]=0};this.X=function(b,c){this.fa(b);this.ba(c);this.da();this.aa();this.ea()}}function Ma(){return 0<Ma.N}
var Na={};function Oa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Pa(a){return this.fromWireType(N[a>>2])}var R={},S={},Qa={};function Ra(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Sa(a,b){a=Ra(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ta(a){var b=Error,c=Sa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ua=void 0;
function Va(a,b,c){function d(h){h=c(h);if(h.length!==a.length)throw new Ua("Mismatched type converter count");for(var k=0;k<a.length;++k)T(a[k],h[k])}a.forEach(function(h){Qa[h]=b});var e=Array(b.length),g=[],l=0;b.forEach(function(h,k){S.hasOwnProperty(h)?e[k]=S[h]:(g.push(h),R.hasOwnProperty(h)||(R[h]=[]),R[h].push(function(){e[k]=S[h];++l;l===g.length&&d(e)}))});0===g.length&&d(e)}
function Wa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Xa=void 0;function U(a){for(var b="";I[a];)b+=Xa[I[a++]];return b}var Ya=void 0;function V(a){throw new Ya(a);}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(S.hasOwnProperty(a)){if(c.W)return;V("Cannot register type '"+d+"' twice")}S[a]=b;delete Qa[a];R.hasOwnProperty(a)&&(b=R[a],delete R[a],b.forEach(function(e){e()}))}var Za=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function $a(a){4<a&&0===--W[a].M&&(W[a]=void 0,Za.push(a))}function ab(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Za.length?Za.pop():W.length;W[b]={M:1,value:a};return b}}function bb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function cb(a,b){switch(b){case 2:return function(c){return this.fromWireType(va[c>>2])};case 3:return function(c){return this.fromWireType(wa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function db(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Sa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function eb(a,b){var c=f;if(void 0===c[a].I){var d=c[a];c[a]=function(){c[a].I.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].I+")!");return c[a].I[arguments.length].apply(this,arguments)};c[a].I=[];c[a].I[d.P]=d}}
function fb(a,b,c){f.hasOwnProperty(a)?((void 0===c||void 0!==f[a].I&&void 0!==f[a].I[c])&&V("Cannot register public name '"+a+"' twice"),eb(a,a),f.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),f[a].I[c]=b):(f[a]=b,void 0!==c&&(f[a].ja=c))}function gb(a,b){for(var c=[],d=0;d<a;d++)c.push(K[(b>>2)+d]);return c}
function hb(a,b){assert(0<=a.indexOf("j"),"getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var e;-1!=a.indexOf("j")?e=c&&c.length?f["dynCall_"+a].apply(null,[b].concat(c)):f["dynCall_"+a].call(null,b):e=G.get(b).apply(null,c);return e}}function X(a,b){a=U(a);var c=-1!=a.indexOf("j")?hb(a,b):G.get(b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}
var ib=void 0;function jb(a){a=kb(a);var b=U(a);Z(a);return b}function lb(a,b){function c(g){e[g]||S[g]||(Qa[g]?Qa[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new ib(a+": "+d.map(jb).join([", "]));}
function mb(a,b,c){switch(b){case 0:return c?function(d){return M[d]}:function(d){return I[d]};case 1:return c?function(d){return J[d>>1]}:function(d){return pa[d>>1]};case 2:return c?function(d){return K[d>>2]}:function(d){return N[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var nb={},ob=[];function pb(a){var b=ob.length;ob.push(a);return b}function qb(a,b){var c=S[a];void 0===c&&V(b+" has unknown type "+jb(a));return c}
function rb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=qb(K[(b>>2)+d],"parameter "+d);return c}var sb=[null,[],[]];Ua=f.InternalError=Ta("InternalError");for(var tb=Array(256),ub=0;256>ub;++ub)tb[ub]=String.fromCharCode(ub);Xa=tb;Ya=f.BindingError=Ta("BindingError");f.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};ib=f.UnboundTypeError=Ta("UnboundTypeError");
Aa.push({S:function(){vb()}});
var xb={d:function(a,b,c,d){B("Assertion failed: "+(a?H(I,a,void 0):"")+", at: "+[b?b?H(I,b,void 0):"":"unknown filename",c,d?d?H(I,d,void 0):"":"unknown function"])},B:function(a){return wb(a+16)+16},x:function(a,b,c){(new La(a)).X(b,c);"uncaught_exception"in Ma?Ma.N++:Ma.N=1;throw a;},b:G,s:function(a){var b=Na[a];delete Na[a];var c=b.Z,d=b.$,e=b.O,g=e.map(function(l){return l.V}).concat(e.map(function(l){return l.ha}));Va([a],g,function(l){var h={};e.forEach(function(k,m){var n=l[m],q=k.T,y=k.U,
z=l[m+e.length],p=k.ga,ka=k.ia;h[k.R]={read:function(A){return n.fromWireType(q(y,A))},write:function(A,F){var Y=[];p(ka,A,z.toWireType(Y,F));Oa(Y)}}});return[{name:b.name,fromWireType:function(k){var m={},n;for(n in h)m[n]=h[n].read(k);d(k);return m},toWireType:function(k,m){for(var n in h)if(!(n in m))throw new TypeError('Missing field:  "'+n+'"');var q=c();for(n in h)h[n].write(q,m[n]);null!==k&&k.push(d,q);return q},argPackAdvance:8,readValueFromPointer:Pa,J:d}]})},z:function(a,b,c,d,e){var g=
Wa(c);b=U(b);T(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var h=M;else if(2===c)h=J;else if(4===c)h=K;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[l>>g])},J:null})},y:function(a,b){b=U(b);T(a,{name:b,fromWireType:function(c){var d=W[c].value;$a(c);return d},toWireType:function(c,d){return ab(d)},argPackAdvance:8,readValueFromPointer:Pa,J:null})},q:function(a,
b,c){c=Wa(c);b=U(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+bb(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:cb(b,c),J:null})},k:function(a,b,c,d,e,g){var l=gb(b,c);a=U(a);e=X(d,e);fb(a,function(){lb("Cannot call "+a+" due to unbound types",l)},b-1);Va([],l,function(h){var k=[h[0],null].concat(h.slice(1)),m=h=a,n=e,q=k.length;2>q&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var y=null!==k[1]&&!1,z=!1,p=1;p<k.length;++p)if(null!==k[p]&&void 0===k[p].J){z=!0;break}var ka="void"!==k[0].name,A="",F="";for(p=0;p<q-2;++p)A+=(0!==p?", ":"")+"arg"+p,F+=(0!==p?", ":"")+"arg"+p+"Wired";m="return function "+Ra(m)+"("+A+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+m+" called with ' + arguments.length + ' arguments, expected "+(q-2)+" args!');\n}\n";z&&(m+="var destructors = [];\n");var Y=z?"destructors":"null";A="throwBindingError invoker fn runDestructors retType classParam".split(" ");
n=[V,n,g,Oa,k[0],k[1]];y&&(m+="var thisWired = classParam.toWireType("+Y+", this);\n");for(p=0;p<q-2;++p)m+="var arg"+p+"Wired = argType"+p+".toWireType("+Y+", arg"+p+"); // "+k[p+2].name+"\n",A.push("argType"+p),n.push(k[p+2]);y&&(F="thisWired"+(0<F.length?", ":"")+F);m+=(ka?"var rv = ":"")+"invoker(fn"+(0<F.length?", ":"")+F+");\n";if(z)m+="runDestructors(destructors);\n";else for(p=y?1:2;p<k.length;++p)q=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==k[p].J&&(m+=q+"_dtor("+q+"); // "+k[p].name+"\n",
A.push(q+"_dtor"),n.push(k[p].J));ka&&(m+="var ret = retType.fromWireType(rv);\nreturn ret;\n");A.push(m+"}\n");k=db(A).apply(null,n);p=b-1;if(!f.hasOwnProperty(h))throw new Ua("Replacing nonexistant public symbol");void 0!==f[h].I&&void 0!==p?f[h].I[p]=k:(f[h]=k,f[h].P=p);return[]})},f:function(a,b,c,d,e){function g(m){return m}b=U(b);-1===e&&(e=4294967295);var l=Wa(c);if(0===d){var h=32-8*c;g=function(m){return m<<h>>>h}}var k=-1!=b.indexOf("unsigned");T(a,{name:b,fromWireType:g,toWireType:function(m,
n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+bb(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+bb(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return k?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:mb(b,l,0!==d),J:null})},e:function(a,b,c){function d(g){g>>=2;var l=N;return new e(L,l[g+1],l[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=U(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{W:!0})},r:function(a,b){b=U(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=N[d>>2];if(c)for(var g=d+4,l=0;l<=e;++l){var h=d+4+l;if(l==e||0==I[h]){g=g?H(I,g,h-g):"";if(void 0===k)var k=g;else k+=String.fromCharCode(0),k+=g;g=h+1}}else{k=Array(e);for(l=0;l<e;++l)k[l]=String.fromCharCode(I[d+4+l]);k=k.join("")}Z(d);return k},toWireType:function(d,e){e instanceof
ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||V("Cannot pass non-string to std::string");var l=(c&&g?function(){for(var m=0,n=0;n<e.length;++n){var q=e.charCodeAt(n);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|e.charCodeAt(++n)&1023);127>=q?++m:m=2047>=q?m+2:65535>=q?m+3:m+4}return m}:function(){return e.length})(),h=wb(4+l+1);N[h>>2]=l;if(c&&g)ma(e,h+4,l+1);else if(g)for(g=0;g<l;++g){var k=e.charCodeAt(g);
255<k&&(Z(h),V("String has UTF-16 code units that do not fit in 8 bits"));I[h+4+g]=k}else for(g=0;g<l;++g)I[h+4+g]=e[g];null!==d&&d.push(Z,h);return h},argPackAdvance:8,readValueFromPointer:Pa,J:function(d){Z(d)}})},j:function(a,b,c){c=U(c);if(2===b){var d=oa;var e=qa;var g=ra;var l=function(){return pa};var h=1}else 4===b&&(d=sa,e=ta,g=ua,l=function(){return N},h=2);T(a,{name:c,fromWireType:function(k){for(var m=N[k>>2],n=l(),q,y=k+4,z=0;z<=m;++z){var p=k+4+z*b;if(z==m||0==n[p>>h])y=d(y,p-y),void 0===
q?q=y:(q+=String.fromCharCode(0),q+=y),y=p+b}Z(k);return q},toWireType:function(k,m){"string"!==typeof m&&V("Cannot pass non-string to C++ string type "+c);var n=g(m),q=wb(4+n+b);N[q>>2]=n>>h;e(m,q+4,n+b);null!==k&&k.push(Z,q);return q},argPackAdvance:8,readValueFromPointer:Pa,J:function(k){Z(k)}})},l:function(a,b,c,d,e,g){Na[a]={name:U(b),Z:X(c,d),$:X(e,g),O:[]}},g:function(a,b,c,d,e,g,l,h,k,m){Na[a].O.push({R:U(b),V:c,T:X(d,e),U:g,ha:l,ga:X(h,k),ia:m})},A:function(a,b){b=U(b);T(a,{Y:!0,name:b,argPackAdvance:0,
fromWireType:function(){},toWireType:function(){}})},m:function(a,b,c,d){a=ob[a];b||V("Cannot use deleted val. handle = "+b);b=W[b].value;var e=nb[c];c=void 0===e?U(c):e;a(b,c,null,d)},h:$a,n:function(a,b){b=rb(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(m){return m.name}).join("_")+"$",e=["retType"],g=[c],l="",h=0;h<a-1;++h)l+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),g.push(b[1+h]);d="return function "+Ra("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var k=0;for(h=0;h<
a-1;++h)d+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(k?"+"+k:"")+");\n",k+=b[h+1].argPackAdvance;d+="    var rv = handle[name]("+l+");\n";for(h=0;h<a-1;++h)b[h+1].deleteObject&&(d+="    argType"+h+".deleteObject(arg"+h+");\n");c.Y||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=db(e).apply(null,g);return pb(a)},i:function(a){4<a&&(W[a].M+=1)},t:function(){return ab([])},o:function(a,b){a=qb(a,"_emval_take_value");a=a.readValueFromPointer(b);return ab(a)},
c:function(){B()},v:function(a,b,c){I.copyWithin(a,b,b+c)},w:function(a){a>>>=0;var b=I.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{E.grow(Math.min(2147483648,d)-L.byteLength+65535>>>16);xa(E.buffer);var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},p:function(a,b,c,d){for(var e=0,g=0;g<c;g++){for(var l=K[b+8*g>>2],h=K[b+(8*g+4)>>2],k=0;k<h;k++){var m=I[l+k],n=sb[a];0===m||
10===m?((1===a?ia:C)(H(n,0)),n.length=0):n.push(m)}e+=h}K[d>>2]=e;return 0},a:E,u:function(){}};
(function(){function a(e){f.asm=e.exports;O--;f.monitorRunDependencies&&f.monitorRunDependencies(O);0==O&&(null!==Ea&&(clearInterval(Ea),Ea=null),P&&(e=P,P=null,e()))}function b(e){a(e.instance)}function c(e){return Ja().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){C("failed to asynchronously prepare wasm: "+g);B(g)})}var d={a:xb};O++;f.monitorRunDependencies&&f.monitorRunDependencies(O);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return C("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(D||"function"!==typeof WebAssembly.instantiateStreaming||Ga()||Fa("file://")||"function"!==typeof fetch)return c(b);fetch(Q,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){C("wasm streaming compile failed: "+g);C("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var vb=f.___wasm_call_ctors=function(){return(vb=f.___wasm_call_ctors=f.asm.C).apply(null,arguments)},wb=f._malloc=function(){return(wb=f._malloc=f.asm.D).apply(null,arguments)},Z=f._free=function(){return(Z=f._free=f.asm.E).apply(null,arguments)},kb=f.___getTypeName=function(){return(kb=f.___getTypeName=f.asm.F).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.G).apply(null,arguments)};
f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.H).apply(null,arguments)};var yb;P=function zb(){yb||Ab();yb||(P=zb)};
function Ab(){function a(){if(!yb&&(yb=!0,f.calledRun=!0,!ja)){Ka(Aa);Ka(Ba);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ca.unshift(b)}Ka(Ca)}}if(!(0<O)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Da();Ka(za);0<O||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
f.run=Ab;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();noExitRuntime=!0;Ab();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Module;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Module; });
    else if (typeof exports === 'object')
      exports["Module"] = Module;
    