name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - run: npm i -g pnpm

      - run: pnpm i

      - name: Build
        run: pnpm run build
        env:
          SENTRY_DSN: https://d101904fac2c486ea6f8563c2cf054af@o253601.ingest.sentry.io/5499968

      - name: Configure domain
        run: echo "ic-analyzer.kaciras.com" > dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          silent: true
          clean: true
          branch: gh-pages
          folder: dist
          single-commit: true
